#!/bin/bash
#SBATCH -A MICHAELIDES-SL3-CPU
#SBATCH --partition=icelake

#SBATCH --job-name=reaxff
#SBATCH --time=00:10:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --qos INTR

source /home/dk584/.bashrc
module purge
module load rhel8/default-icl

#python3 make_lammps_atoms.py

#python3 modify.py

mpirun -n 32 lmp -partition 32x1 -in input.txt

./make_xyz
rm dump.neb* final* screen* log.lammps* tmp.lammps.variable 

